export const REQUEST_RECENT_TRACKS = 'REQUEST_RECENT_TRACKS'

export const REQUEST_ARTIST_INFO = 'REQUEST_ARTIST_INFO'

export const REQUEST_LIBRARY_CONTAINS = 'REQUEST_LIBRARY_CONTAINS'

export const SAVE_TRACK_TO_LIBRARY = 'SAVE_TRACK_TO_LIBRARY'

export const REMOVE_TRACK_FROM_LIBRARY = 'REMOVE_TRACK_FROM_LIBRARY'
