export const SET_RECENT_TRACKS = 'SET_RECENT_TRACKS'
export const SET_ARTISTS_INFO = 'SET_ARTISTS_INFO'
export const ADD_ARTISTS_INFO = 'ADD_ARTISTS_INFO'
export const ADD_LIBRARY_CONTAINS_INFO = 'ADD_LIBRARY_CONTAINS_INFO'
export const SET_LIBRARY_CONTAINS_INFO = 'SET_LIBRARY_CONTAINS_INFO'

export const SET_UI_LOADING = 'SET_UI_LOADING'
export const SET_UI_ERROR = 'SET_UI_ERROR'
export const SET_UI_CURRENTLY_PLAYING_TRACK = 'SET_UI_CURRENTLY_PLAYING_TRACK'

export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'
export const RESET_AUTHENTICATION = 'RESET_AUTHENTICATION'
